# Generated by Django 3.1.4 on 2020-12-18 14:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201218_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publicado',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 18, 14, 47, 35, 563951, tzinfo=utc)),
        ),
    ]
